config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get 'about' => 'welcome#about'

  resources :boards do
    resources :bulletins, except: [:index]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  has_many :bulletins
end

app/models/bulletin.rb
class Bulletin < ApplicationRecord
  belongs_to :board
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController

  def show
    @board = Board.find(params[:id])
  end




end

app/controllers/bulletins_controller.rb
class BulletinsController < ApplicationController

  def show
  end


  def new
    @board = Board.find(params[:board_id])
    @bulletin = Bulletin.new
  end


  def create
    @bulletin = Bulletin.new
    @bulletin.title = params[:bulletin][:title]
    @bulletin.body = params[:bulletin][:body]
    @board = Board.find(params[:board_id])
    @bulletin.board = @board

    if @bulletin.save
      flash[:notice] = "Bulletin was saved."
      redirect_to [@board]
    else
      flash.now[:alert] = "There was an error saving. Please try again."
      render :new
    end
  end


  def edit
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/bulletins_helper.rb
module BulletinsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/boards/show.html.erb
<h1 ><%= @board.title %></h1>
<h4>Share your bulletins here</h4>

<div class="row">
  <div class="col" style="background-image: url(<%= asset_path 'cork_board.jpg' %>); max-width: 100%; min-height: 600px; margin-left:0; margin-right:0;">
    <div class="row" style="margin-right:25px; margin-left:25px;">
      <div class="col" style="margin-top: 25px; margin-bottom:25px;">
        <% if @board.bulletins %>
          <%= render 'bulletins/bulletins_on_board', board: @board %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="row top-buffer" style="margin-left:0; margin-right:0;">
  <%= link_to "Add Bulletin", new_board_bulletin_path(@board), class: "btn btn-primary" %>
</div>

app/views/bulletins/_bulletins.html.erb
<h1>All Bulletins</h1>

<% @bulletins.each do |bulletin| %>
  <p><%= link_to bulletin.title, bulletin_path(bulletin.id) %></p>
<% end %>

app/views/bulletins/_bulletins_on_board.html.erb
  <% counter = 0 %>
  <div class="row text-center text-lg-left row-eq-height">

    <% @board.bulletins.each do |bulletin| %>
      <% if (counter != 0 && counter % 4 == 0) %>
        </div>
        <div class="row text-center text-lg-left row-eq-height">
      <% end %>

      <div class="col-lg-3">
        <div class="thumbnail" style="height:180px;">
          <h3><%= bulletin.title %></h3>
          <div class="caption">
            <p><%= bulletin.body %></p>
          </div>
        </div>
      </div>

      <% counter = counter + 1 %>
    <% end %>

app/views/bulletins/edit.html.erb
<h1>Bulletins#edit</h1>
<p>Find me in app/views/bulletins/edit.html.erb</p>

app/views/bulletins/index.html.erb
<h1>Bulletins#index</h1>
<p>Find me in app/views/bulletins/index.html.erb</p>

app/views/bulletins/new.html.erb
<div class="row">
  <div class="col-md-6">
    <h1>uPost Board</h1>
    <%= form_for [@board, @bulletin] do |f| %>

      <div class="form-group form-group-lg">
        <%= f.label :title, class: "hidden" %>
        <%= f.text_field :title, class: 'form-control text-center', placeholder: "Enter Bulletin Title" %>
      </div>

      <div class="form-group">
        <%= f.label :body, class: "hidden" %>
        <%= f.text_area :body, rows: 17, class: 'form-control text-center', placeholder: "Enter bulletin body" %>
      </div>

      <div class="pull-left form-group">
        <%= f.submit "Post", class: 'btn btn-lg btn-success' %>
      </div>

      <div class="pull-right">
        <%= link_to "Cancel", @board, class: 'btn btn-lg btn-danger' %>
      </div>

    <% end %>
  </div>
</div>

app/views/bulletins/show.html.erb
<div class="row">
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <img src="..." alt="...">
      <div class="caption">
        <h3>Thumbnail label</h3>
        <p>...</p>
        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Upost</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <ul class="nav nav-tabs">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Board", board_path(Board.first_or_create(title: 'uPost') ) %></li>
        <li><%= link_to "About", about_path %></li>
      </ul>

      <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-warning">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>


      <%= yield %>


    </div>
  </body>
</html>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>